"""
Django settings for VulneryAPI project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from importlib.resources import path
from pathlib import Path
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m&di8z+6_ai95w&#8#kfi#78y5#eh^@1k+_@*vg64!pk*klbqv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost","13.59.208.186"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VulneryAPI.urls'

PATH_TEMPLATES = [f"{BASE_DIR}/VulnsPoster/Templates",f"{BASE_DIR}/Dashboards/Templates",f"{BASE_DIR}/VulneryAPI/Templates"]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': PATH_TEMPLATES,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VulneryAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#ELASTIC SEARCH

ELASTIC_SEARCH = {
    "ELASTIC_CONNECTION":{
        "URL":"18.216.127.249",
        "PORT": 9200
    },
    "ELASTIC_CREDENTIALS":{
        "username":"elastic",
        "password":"u5esjkJ2lJFRd*VwqNW9"
    },
    "ELASTIC_INDEX":{
        "sast_vulns":"sast_vulns",
        "dast_vulns":"dast_vulns",
        "infra_vulns":"infra_vulns"
    }
}

#VULN TYPES

VULN_TYPES = {
    "SAST_Vulns":"SAST",
    "DAST_Vulns":"DAST",
    "Infra_Vulns":"Infra"
}

#VULN SEVERITIES

VULN_SEVERITY = [
    {
        "SEV":"High"
    },
    {
        "SEV":"Medium"
    },
    {
        "SEV":"Low"
    },
    {
        "SEV":"Info"
    }
]

#VULN STATUS

VULN_STATUS = [
    {
        "STATUS":"Open"
    },
    {
        "STATUS":"Closed"
    },
    {
        "STATUS":"False Positive"
    }
]

#ALL (To bring all severities or status)

ALL = "All"

#LOGGER

LOGGER_APP_NAMES = {
    "VulnsPoster":"VulnsPoster",
    "VulneryAPI":"VulneryAPI",
    "Dashboards":"Dashboards"
}

#Login

LOGIN = ['username','password']

#Admin

ADMIN = {
    "username":"DevSecOpsDTT",
    "password":"dtt@DevSeCoPs*2022_"
}

#KEYS

MASTER_TOKEN = "36e5a155c737f06e9985af519b1c033005a0a4f802969ffb531f8ec8d3166b42"
CSRF_TOKEN = ""
AES_KEY = "bPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq"

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = PATH_TEMPLATES

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


mimetypes.add_type("application/javascript", ".js", True)
